- hosts: localhost
  tasks:
  - name: install ec2
    amazon.aws.ec2:
      key_name: ec2ansible
      instance_type: t2.micro
      image: ami-08f63db601b82ff5f
      count: 1
      vpc_subnet_id: subnet-c791d38b
      assign_public_ip: yes
